name: homework1
dependencies:
- cycler=0.10.0=py27_0
- freetype=2.5.5=1
- libpng=1.6.22=0
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- nose=1.3.7=py27_1
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- pip=8.1.2=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scikit-learn=0.17.1=np111py27_2
- scipy=0.18.0=np111py27_0
- setuptools=25.1.6=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - untangle==1.1.0

